#!/usr/bin/env python3
"""one-off-writer: LLM-generated first-touch email from the scored mart.

Run:
    python3 skills/one-off-writer/run.py --ccn 450046
    python3 skills/one-off-writer/run.py --ccns 500064,310009,330101,450046,190064
"""
from __future__ import annotations
import argparse
import csv
import json
import os
import re
from datetime import date
from pathlib import Path

import httpx

ROOT = Path(__file__).resolve().parents[2]
MART = ROOT / 'data' / 'mart' / 'tam_scored.csv'
OUT_DIR = ROOT / 'documents' / 'qso-briefs' / 'auto'

ANTHROPIC_URL = 'https://api.anthropic.com/v1/messages'
MODEL = 'claude-haiku-4-5-20251001'
MAX_TOKENS = 600

SYSTEM = """You are writing a high-context one-off email for Firefly's GTM team.
Firefly sells a unified AI + IoT physical-safety platform (Ember software + Lattice
hardware: panic buttons, gunshot detection, resilient no-IT private-network gateway).

HARD RULES (non-negotiable):
- ONE-OFF only. Never write or imply a sequence.
- 80-125 words. Tight. No fluff.
- Lead with a SPECIFIC signal — the most concrete fact in the data (an OSHA-documented
  incident, a mandate deadline, an exec change). Do not lead with platitudes.
- Pivot to Firefly's Detect→Locate→Alert→Respond job-to-be-done, naming the specific
  product (Ember or Lattice) relevant to the situation.
- Close with a soft, specific ask (a 15-min meeting OR a proof artifact OR an analysis
  offer). Never a calendar link, never a calendly URL.
- No emojis, no exclamation marks, no superlatives ("game-changing", "world-class").
- Sign off as "— Ryan" (the Firefly rep).
- If the facility has an active lawsuit signal (OLOL/Inner Parish), be reverent
  — don't reference the litigation as leverage. The auto-writer rarely has this
  context; default to careful tone.
""".strip()

USER_TEMPLATE = """Write the one-off email for this facility. Return ONLY a markdown
document with this EXACT structure:

```
**To:** <recommended role>, <facility name>
**CC:** <recommended internal stakeholder role>
**Subject:** <subject line — tight, specific, no fluff>

<email body — 80-125 words>

— Ryan

---
**Why this opening:** <one sentence — what specific signal you led with and why>
```

Facility data:
```json
{FACTS}
```

Write it now."""

def load_env():
    env = ROOT / '.env'
    if env.exists():
        for line in env.read_text().splitlines():
            if '=' in line and not line.strip().startswith('#'):
                k, v = line.split('=', 1)
                v = v.split('#', 1)[0].strip()
                if v:
                    os.environ.setdefault(k.strip(), v)

def slugify(s: str) -> str:
    return re.sub(r'[^A-Za-z0-9]+', '-', s.lower()).strip('-')[:50]

def write_email(ccn: str) -> Path | None:
    row = None
    with open(MART, encoding='utf-8') as f:
        for r in csv.DictReader(f):
            if r['ccn'] == ccn:
                row = r
                break
    if not row:
        print(f'  ! CCN {ccn} not found')
        return None
    keep = ['ccn', 'facility_name', 'parent_system', 'state', 'city', 'beds',
            'has_ED', 'has_behavioral_unit', 'hospital_type',
            'mandate_name', 'mandate_status_display', 'effective_date',
            'forge_total', 'forge_tier', 'edm_seed_title',
            'osha_severe_injury_count_24mo', 'osha_first_evidence_date',
            'osha_first_evidence_nature', 'osha_evidence_natures',
            'hos_highdpp', 'hos_highuc', 'hos_majteach',
            'acute_need_evidence', 'event_evidence', 'gravity_evidence']
    facts = {k: row.get(k, '') for k in keep if row.get(k)}
    user = USER_TEMPLATE.replace('{FACTS}', json.dumps(facts, indent=2))
    key = os.environ.get('ANTHROPIC_API_KEY')
    resp = httpx.post(
        ANTHROPIC_URL,
        headers={'x-api-key': key, 'anthropic-version': '2023-06-01', 'content-type': 'application/json'},
        json={
            'model': MODEL,
            'max_tokens': MAX_TOKENS,
            'system': SYSTEM,
            'messages': [{'role': 'user', 'content': user}],
        },
        timeout=60.0,
    )
    if resp.status_code != 200:
        raise RuntimeError(f'Anthropic {resp.status_code}: {resp.text[:400]}')
    d = resp.json()
    text = d['content'][0]['text']
    usage = d['usage']
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    slug = slugify(row['facility_name'])
    out = OUT_DIR / f'one-off-{ccn}-{slug}.md'
    header = (
        f'<!-- AUTO-GENERATED by skills/one-off-writer on '
        f'{date.today().isoformat()} using {MODEL} -->\n'
        f'<!-- in/out tokens: {usage.get("input_tokens","?")}/{usage.get("output_tokens","?")} -->\n\n'
        f'# One-off — {row["facility_name"]} ({row["state"]})\n\n'
    )
    out.write_text(header + text)
    cost = (usage.get('input_tokens',0)*1 + usage.get('output_tokens',0)*5) / 1_000_000
    print(f'    → {out.relative_to(ROOT)} · '
          f'in/out {usage.get("input_tokens","?")}/{usage.get("output_tokens","?")} (~${cost:.4f})')
    return out

def main():
    load_env()
    ap = argparse.ArgumentParser()
    ap.add_argument('--ccn')
    ap.add_argument('--ccns')
    args = ap.parse_args()
    ccns = [args.ccn] if args.ccn else (
        [c.strip() for c in args.ccns.split(',')] if args.ccns else [])
    if not ccns:
        ap.print_help(); return
    print(f'\nwriting {len(ccns)} one-off(s)...')
    for ccn in ccns:
        try:
            write_email(ccn)
        except Exception as e:
            print(f'  ! {ccn}: {e}')
    print(f'\ndone. outputs in {OUT_DIR.relative_to(ROOT)}')

if __name__ == '__main__':
    main()
