#!/usr/bin/env python3
"""compliance: per-state mandate-conformance docs (template-based, no LLM).

For each priority state, reads the mandate from data/reference/mandates.csv,
maps requirement themes → Firefly product coverage via product-coverage.yaml,
writes a structured compliance doc to documents/compliance/<XX>.md.

Run:
    python3 skills/compliance/run.py --all
    python3 skills/compliance/run.py --state WA
"""
from __future__ import annotations
import argparse
import csv
import re
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
MANDATES = ROOT / 'data' / 'reference' / 'mandates.csv'
COVERAGE = Path(__file__).parent / 'product-coverage.yaml'
OUT_DIR = ROOT / 'documents' / 'compliance'

# 15 priority states + their full names
PRIORITY = {
    'WA': 'Washington', 'CA': 'California', 'NY': 'New York', 'NJ': 'New Jersey',
    'LA': 'Louisiana', 'FL': 'Florida', 'IL': 'Illinois', 'TX': 'Texas',
    'AZ': 'Arizona', 'MA': 'Massachusetts', 'NC': 'North Carolina', 'OR': 'Oregon',
    'CO': 'Colorado', 'CT': 'Connecticut', 'MD': 'Maryland',
}

def parse_yaml_simple(path: Path) -> dict:
    """Tiny YAML parser for our flat structure (no full PyYAML dep)."""
    out = {'themes': {}}
    cur_theme = None
    cur_field = None
    cur_lines = []
    with open(path) as f:
        for line in f:
            raw = line.rstrip('\n')
            if not raw.strip() or raw.lstrip().startswith('#'):
                continue
            stripped = raw.strip()
            indent = len(raw) - len(raw.lstrip())
            if indent == 0:
                continue
            if indent == 2 and stripped.endswith(':'):
                if cur_field == 'firefly_coverage' and cur_lines:
                    out['themes'][cur_theme]['firefly_coverage'] = '\n'.join(cur_lines).strip()
                    cur_lines = []
                cur_theme = stripped[:-1]
                out['themes'][cur_theme] = {}
                cur_field = None
            elif indent == 4 and ':' in stripped:
                if cur_field == 'firefly_coverage' and cur_lines:
                    out['themes'][cur_theme]['firefly_coverage'] = '\n'.join(cur_lines).strip()
                    cur_lines = []
                k, _, v = stripped.partition(':')
                v = v.strip()
                cur_field = k
                if v == '|':
                    cur_lines = []
                elif v.startswith('['):
                    items = [s.strip() for s in v.strip('[]').split(',') if s.strip()]
                    out['themes'][cur_theme][k] = items
                else:
                    out['themes'][cur_theme][k] = v
            elif indent >= 6 and cur_field == 'firefly_coverage':
                cur_lines.append(stripped)
        if cur_field == 'firefly_coverage' and cur_lines:
            out['themes'][cur_theme]['firefly_coverage'] = '\n'.join(cur_lines).strip()
    return out

def classify_requirement(req: str, themes: dict) -> list[str]:
    """Return list of theme names whose keywords match the requirement text."""
    req_lower = req.lower()
    hits = []
    for theme_name, theme_data in themes.items():
        if theme_name == 'default':
            continue
        for kw in theme_data.get('requirement_keywords', []):
            if kw.lower() in req_lower:
                hits.append(theme_name)
                break
    return hits or ['default']

STATE_NAME_TO_CODE = {v.upper(): k for k, v in PRIORITY.items()}

def state_from_jurisdiction(j: str) -> str | None:
    j = (j or '').upper()
    for name, code in STATE_NAME_TO_CODE.items():
        if name in j:
            return code
    return None

def generate_for_state(state_code: str, mandates: list[dict], coverage: dict) -> Path | None:
    state_name = PRIORITY[state_code]
    state_mandates = [
        m for m in mandates
        if state_from_jurisdiction(m.get('Jurisdiction', '')) == state_code
        and (m.get('Vertical') or '').strip().lower() in ('healthcare', 'cross-vertical', 'federal')
        and 'dead' not in (m.get('Status') or '').lower()
        and 'vetoed' not in (m.get('Status') or '').lower()
    ]
    if not state_mandates:
        print(f'  {state_code}: no actionable mandates'); return None
    primary = state_mandates[0]
    requirement = (primary.get('Requirement (short)') or '').strip()
    themes = classify_requirement(requirement, coverage['themes'])

    out = OUT_DIR / f'{state_code}-{state_name.lower().replace(" ", "-")}.md'
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    lines = [
        f'<!-- AUTO-GENERATED by skills/compliance on {date.today().isoformat()} -->',
        f'<!-- template-based; no LLM used -->',
        '',
        f'# Compliance Conformance — Firefly × {state_name} ({state_code})',
        '',
        '## Primary mandate',
        '',
        f'**{primary.get("Law / Bill", "").strip()}** ({primary.get("Type", "").strip()})',
        '',
        f'- **Jurisdiction**: {primary.get("Jurisdiction", "").strip()}',
        f'- **Status**: {primary.get("Status", "").strip()}',
        f'- **Effective / Deadline**: {primary.get("Effective / Deadline", "").strip()}',
        f'- **Source**: {primary.get("Source", "").strip()}',
        f'- **Requirement (short)**: {requirement}',
        '',
        '## Firefly coverage by requirement theme',
        '',
        'The mandate above maps to the following requirement themes; Firefly\'s coverage per theme:',
        '',
    ]
    for theme_name in themes:
        theme = coverage['themes'].get(theme_name, coverage['themes']['default'])
        lines.append(f'### {theme_name.replace("_", " ").title()}')
        lines.append('')
        lines.append(theme['firefly_coverage'])
        lines.append('')
    if len(state_mandates) > 1:
        lines.append('## Other related statutes in this state')
        lines.append('')
        for m in state_mandates[1:]:
            lines.append(
                f'- **{m.get("Law / Bill", "").strip()}** '
                f'({m.get("Status", "").strip()}) — {m.get("Source", "").strip()}'
            )
        lines.append('')
    lines.append('## What this doc is NOT')
    lines.append('')
    lines.append(
        '- Not a substitute for legal review. Conformance claims must be validated '
        'by counsel before any external use.'
    )
    lines.append(
        '- Not a customer commitment. Specific coverage depends on the deployment '
        'configuration (modules enabled, integrations, training).'
    )
    lines.append(
        '- Generated automatically from `data/reference/mandates.csv` + '
        '`skills/compliance/product-coverage.yaml`. Update either to refresh.'
    )

    out.write_text('\n'.join(lines) + '\n')
    print(f'  → {out.relative_to(ROOT)}')
    return out

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--all', action='store_true')
    ap.add_argument('--state', help='single state code (e.g. WA)')
    args = ap.parse_args()
    mandates = list(csv.DictReader(open(MANDATES)))
    coverage = parse_yaml_simple(COVERAGE)
    print(f'\nproduct-coverage themes: {list(coverage["themes"].keys())}')
    print(f'mandates loaded: {len(mandates)}')
    print()
    if args.state:
        if args.state.upper() not in PRIORITY:
            print(f'! {args.state} not in priority 15'); return
        generate_for_state(args.state.upper(), mandates, coverage)
    elif args.all:
        for code in PRIORITY:
            generate_for_state(code, mandates, coverage)
    else:
        ap.print_help()

if __name__ == '__main__':
    main()
