#!/usr/bin/env python3
"""account-researcher: LLM-generated pre-call brief from the scored mart.

Reads a CCN, pulls the row from data/mart/tam_scored.csv, calls Claude Haiku 4.5
with a structured prompt + Firefly positioning context, writes the brief to
documents/qso-briefs/auto/qso-auto-<ccn>-<slug>.md.

Run:
    python3 skills/account-researcher/run.py --ccn 450184
    python3 skills/account-researcher/run.py --ccns 450184,500064,310009
    python3 skills/account-researcher/run.py --top 10
"""
from __future__ import annotations
import argparse
import csv
import json
import os
import re
import sys
from datetime import date
from pathlib import Path

import httpx

ROOT = Path(__file__).resolve().parents[2]
MART = ROOT / 'data' / 'mart' / 'tam_scored.csv'
OUT_DIR = ROOT / 'documents' / 'qso-briefs' / 'auto'

ANTHROPIC_URL = 'https://api.anthropic.com/v1/messages'
MODEL = 'claude-haiku-4-5-20251001'
MAX_TOKENS = 1800

# Firefly positioning context — kept tight for prompt efficiency
FIREFLY_CONTEXT = """
You are writing a pre-call brief for Firefly's GTM team. Firefly is a unified AI + IoT
physical-safety platform (Ember software + Lattice hardware: panic buttons, gunshot
detection, resilient no-IT private-network gateway). Job-to-be-done: Detect → Locate →
Alert → Respond. Primary moat: trusted-standard / regulatory.

Firefly's playbook in healthcare:
- Greenfield → mandate-readiness story before enforcement
- Legacy/EOL incumbent → clean migration
- Replace-layer competitor (CENTEGIX, Strongline, React Mobile) → coverage + total-cost side-by-side
- Integrate-layer (Genetec/Milestone cameras) → neutral, Firefly integrates

NON-NEGOTIABLE: one-offs only, never email sequences. Every signal must carry a public
evidence URL. Never fabricate. Unknown fields = explicit "Tier-B/C enrichment pending".
""".strip()

BRIEF_TEMPLATE_INSTRUCTIONS = """
Generate a markdown pre-call brief in EXACTLY this structure:

# QSO Auto-Brief — {FACILITY_NAME} ({STATE})

**Status**: forge_total **{TOTAL}** · facility_tier **{TIER_NUM}** · forge_tier **{TIER}**

## Account at a glance
A table with: CCN, Beds, ED/BH, Hospital type, Parent system, Ownership, Safety-net flags (AHRQ)

## FORGE rationale
Three bullets, one per dimension. Cite the actual rationale text from the data.
- **Acute = X** — <rationale from data + any OSHA evidence>
- **Event = X** — <mandate name, status, effective date>
- **Gravity = X** — <EDM title from NPPES, beds, system size>

## The signal that makes this account interesting
A 2-3 paragraph narrative. If OSHA evidence exists, lead with it (cite the date + nature).
If no OSHA but mandate is In-force, lead with the regulatory enforcement angle.
If mandate is Upcoming, lead with the beat-the-clock angle.
NEVER fabricate incidents. If the engine has no specific incident data, say so explicitly:
"No facility-specific WPV incident surfaces in our engine (Tier-B news/Tier-C hand-research pending)."

## Buying committee
| Role | Notes |
|---|---|
| EDM (NPPES seed) | The actual edm_title from data + caveat "name redacted from public dashboard" |
| Likely champion | Suggest role only (VP Security / VP Patient Safety / Director of Emergency Management). Mark "name pending Tier-B" |
| Sponsor | Likely the CEO/CFO of the parent system. Mark "name pending Tier-B" |

## What we DON'T know yet (honest)
- Incumbent vendor: pending Tier-B (Apify or BidNet)
- Contract expiry: pending Tier-B
- Named security director: pending Tier-C (hand-research or Apollo)
- Recent WPV incident beyond OSHA: pending Tier-B (news at scale)

## The play
Based on the signal stack, recommend ONE of: greenfield, displacement, competitive,
or scale-out (for peer-leaders). Write a 1-paragraph rationale.

## Recommended one-off opening
Suggest ONE sentence the rep should lead with. Be specific to this facility's signals.
Do NOT draft the full email (that's the One-off Writer's job).

## Sources
List every URL referenced in this brief. Be honest — if there are no public evidence
URLs for the OSHA/mandate/etc, say so.

End with a footer noting: this brief was auto-generated by skills/account-researcher
using Haiku 4.5 — the 5 hand-picked QSO briefs (documents/qso-briefs/qso-N-*.md) include
hand-research signals that the engine alone cannot surface.
""".strip()

def load_env():
    env = ROOT / '.env'
    if env.exists():
        for line in env.read_text().splitlines():
            if '=' in line and not line.strip().startswith('#'):
                k, v = line.split('=', 1)
                v = v.split('#', 1)[0].strip()
                if v:
                    os.environ.setdefault(k.strip(), v)

def read_mart_row(ccn: str) -> dict | None:
    with open(MART, encoding='utf-8') as f:
        for r in csv.DictReader(f):
            if r['ccn'] == ccn:
                return r
    return None

def slugify(s: str) -> str:
    s = re.sub(r'[^A-Za-z0-9]+', '-', s.lower()).strip('-')
    return s[:50]

def build_user_prompt(row: dict) -> str:
    # Render the row as a clean JSON-ish block for the LLM
    keep_keys = [
        'ccn', 'facility_name', 'parent_system', 'facilities_in_system',
        'state', 'city', 'beds', 'has_ED', 'has_behavioral_unit',
        'hospital_type', 'ownership', 'hos_majteach', 'hos_highdpp', 'hos_highuc',
        'mandate_name', 'mandate_status', 'mandate_status_display',
        'mandate_scope', 'effective_date',
        'forge_total', 'forge_tier', 'forge_rationale', 'fit_pass',
        'acute_need', 'event', 'gravity',
        'acute_need_evidence', 'event_evidence', 'gravity_evidence',
        'edm_seed_title',
        'osha_severe_injury_count_24mo', 'osha_first_evidence_url',
        'osha_first_evidence_date', 'osha_first_evidence_nature',
        'osha_evidence_natures', 'osha_first_evidence_id',
    ]
    facts = {k: row.get(k, '') for k in keep_keys if row.get(k)}
    return (
        BRIEF_TEMPLATE_INSTRUCTIONS
        + '\n\n## Facility data (everything the engine knows):\n```json\n'
        + json.dumps(facts, indent=2)
        + '\n```\n\nWrite the brief now. Stay tight. No fluff.'
    )

def call_haiku(system: str, user: str) -> tuple[str, dict]:
    key = os.environ.get('ANTHROPIC_API_KEY')
    if not key:
        raise SystemExit('ANTHROPIC_API_KEY not set in .env')
    resp = httpx.post(
        ANTHROPIC_URL,
        headers={
            'x-api-key': key,
            'anthropic-version': '2023-06-01',
            'content-type': 'application/json',
        },
        json={
            'model': MODEL,
            'max_tokens': MAX_TOKENS,
            'system': system,
            'messages': [{'role': 'user', 'content': user}],
        },
        timeout=60.0,
    )
    if resp.status_code != 200:
        raise RuntimeError(f'Anthropic {resp.status_code}: {resp.text[:400]}')
    d = resp.json()
    text = d.get('content', [{}])[0].get('text', '')
    usage = d.get('usage', {})
    return text, usage

def generate_one(ccn: str) -> Path | None:
    row = read_mart_row(ccn)
    if not row:
        print(f'  ! CCN {ccn} not found in mart')
        return None
    name = row.get('facility_name', '')
    print(f'  → researching CCN {ccn} · {name[:50]}')
    user = build_user_prompt(row)
    text, usage = call_haiku(FIREFLY_CONTEXT, user)
    slug = slugify(name)
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    out = OUT_DIR / f'qso-auto-{ccn}-{slug}.md'
    # prepend a header so the brief is identifiable as auto-generated
    header = (
        f'<!-- AUTO-GENERATED by skills/account-researcher on '
        f'{date.today().isoformat()} using {MODEL} -->\n'
        f'<!-- input tokens: {usage.get("input_tokens","?")} · '
        f'output tokens: {usage.get("output_tokens","?")} -->\n\n'
    )
    out.write_text(header + text)
    cost_est = (usage.get('input_tokens',0) * 1 + usage.get('output_tokens',0) * 5) / 1_000_000
    print(f'    wrote {out.relative_to(ROOT)} · '
          f'in/out {usage.get("input_tokens","?")}/{usage.get("output_tokens","?")} tokens '
          f'(~${cost_est:.4f})')
    return out

def main():
    load_env()
    ap = argparse.ArgumentParser()
    ap.add_argument('--ccn', help='single CCN')
    ap.add_argument('--ccns', help='comma-separated CCNs')
    ap.add_argument('--top', type=int, help='top N FORGE-A facilities')
    args = ap.parse_args()
    ccns = []
    if args.ccn: ccns = [args.ccn]
    elif args.ccns: ccns = [c.strip() for c in args.ccns.split(',') if c.strip()]
    elif args.top:
        rows = list(csv.DictReader(open(MART)))
        rows = [r for r in rows if r.get('forge_tier') == 'A']
        rows.sort(key=lambda r: int(r.get('forge_total') or 0), reverse=True)
        ccns = [r['ccn'] for r in rows[:args.top]]
    if not ccns:
        ap.print_help(); return
    print(f'\nresearching {len(ccns)} facility(ies)...')
    total_cost = 0
    for ccn in ccns:
        try:
            generate_one(ccn)
        except Exception as e:
            print(f'  ! {ccn}: {e}')
    print(f'\ndone. outputs in {OUT_DIR.relative_to(ROOT)}')

if __name__ == '__main__':
    main()
